primary: 
	gcc example-fileops.c -o example-fileops; ./example-fileops

unix-writes: 
	gcc compare-writes.c -o compare-writes; ./compare-writes test-file.txt

binary-write: 
	gcc write-example.c -o write-example; ./write-example